import {
  MasterClientRecord,
  AdminAppointment,
  AdminVisit,
  AdminReport,
  AdminAgreement,
  AdminInvoice,
  AdminSubscription,
  AdminNotification,
  AuditActivityLog,
  AdminStats,
} from "../types/admin";

export const MOCK_ADMIN_STATS: AdminStats = {
  activeClientsCount: 128,
  activeClientsDelta: "+8 this month",
  pendingOnboardingCount: 7,
  upcomingVisitsCount: 18,
  reportsPendingCount: 5,
  paymentsDueCount: 4,
  renewalsUpcomingCount: 11,
  attentionItemsCount: 19,
};

export const MOCK_ADMIN_CLIENTS: MasterClientRecord[] = [
  {
    id: "AW-1001",
    firstName: "John",
    lastName: "Miller",
    email: "john.miller@example.com",
    phone: "(401) 212-3002",
    address: {
      street: "142 Wayland Ave",
      city: "Providence",
      state: "RI",
      zip: "02906",
    },
    planName: "Guardian Plus",
    status: "active",
    agreementStatus: "executed",
    agreementSignedDate: "Aug 17, 2026",
    paymentStatus: "paid",
    nextVisitDate: "2026-09-15",
    renewalDate: "2026-09-01",
    totalVisitsAllowed: 12,
    completedVisitsCount: 8,
    remainingVisitsCount: 4,
    createdAt: "2026-03-01",
    notes:
      "Requires ground-floor entrance access. Family contact: Sarah Miller.",
  },
  {
    id: "AW-1002",
    firstName: "Mary",
    lastName: "Jones",
    email: "mary.jones@example.com",
    phone: "(401) 555-0812",
    address: {
      street: "88 Hope Street",
      city: "Providence",
      state: "RI",
      zip: "02906",
    },
    planName: "Essential Guard",
    status: "active",
    agreementStatus: "executed",
    agreementSignedDate: "Aug 10, 2026",
    paymentStatus: "paid",
    nextVisitDate: "2026-09-18",
    renewalDate: "2026-09-01",
    totalVisitsAllowed: 6,
    completedVisitsCount: 4,
    remainingVisitsCount: 2,
    createdAt: "2026-04-12",
  },
  {
    id: "AW-1003",
    firstName: "Robert",
    lastName: "Brown",
    email: "robert.brown@example.com",
    phone: "(401) 555-0433",
    address: {
      street: "210 Broadway",
      city: "Pawtucket",
      state: "RI",
      zip: "02860",
    },
    planName: "Guardian Plus",
    status: "agreement_pending",
    agreementStatus: "pending_signature",
    paymentStatus: "pending",
    renewalDate: "2026-09-01",
    totalVisitsAllowed: 12,
    completedVisitsCount: 0,
    remainingVisitsCount: 12,
    createdAt: "2026-08-16",
    notes: "Agreement sent via email. Awaiting e-signature from daughter.",
  },
  {
    id: "AW-1004",
    firstName: "Patricia",
    lastName: "Davis",
    email: "patricia.davis@example.com",
    phone: "(401) 555-0911",
    address: {
      street: "45 Elmwood Ave",
      city: "Cranston",
      state: "RI",
      zip: "02910",
    },
    planName: "Guardian Plus",
    status: "payment_failed",
    agreementStatus: "executed",
    agreementSignedDate: "Aug 02, 2026",
    paymentStatus: "failed",
    nextVisitDate: "2026-09-20",
    renewalDate: "2026-09-01",
    totalVisitsAllowed: 12,
    completedVisitsCount: 6,
    remainingVisitsCount: 6,
    createdAt: "2026-02-15",
    notes: "Monthly auto-charge declined. Follow up with billing department.",
  },
  {
    id: "AW-1005",
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@example.com",
    phone: "(401) 555-0722",
    address: {
      street: "19 Post Road",
      city: "Warwick",
      state: "RI",
      zip: "02886",
    },
    planName: "Cleaning Add-On",
    status: "active",
    agreementStatus: "executed",
    agreementSignedDate: "Jul 28, 2026",
    paymentStatus: "paid",
    nextVisitDate: "2026-09-22",
    renewalDate: "2026-09-01",
    totalVisitsAllowed: 6,
    completedVisitsCount: 3,
    remainingVisitsCount: 3,
    createdAt: "2026-05-20",
  },
  {
    id: "AW-1006",
    firstName: "Linda",
    lastName: "Taylor",
    email: "linda.taylor@example.com",
    phone: "(401) 555-0344",
    address: {
      street: "303 Main St",
      city: "Woonsocket",
      state: "RI",
      zip: "02895",
    },
    planName: "Guardian Plus",
    status: "payment_pending",
    agreementStatus: "signed",
    agreementSignedDate: "Aug 15, 2026",
    paymentStatus: "pending",
    renewalDate: "2026-09-01",
    totalVisitsAllowed: 12,
    completedVisitsCount: 0,
    remainingVisitsCount: 12,
    createdAt: "2026-08-14",
  },
  {
    id: "AW-1007",
    firstName: "William",
    lastName: "Anderson",
    email: "william.anderson@example.com",
    phone: "(401) 555-0899",
    address: {
      street: "12 Narragansett Blvd",
      city: "Newport",
      state: "RI",
      zip: "02840",
    },
    planName: "Essential Guard",
    status: "cancelled",
    agreementStatus: "executed",
    agreementSignedDate: "Jan 12, 2026",
    paymentStatus: "paid",
    renewalDate: "2026-08-31",
    totalVisitsAllowed: 6,
    completedVisitsCount: 6,
    remainingVisitsCount: 0,
    createdAt: "2026-01-10",
    notes: "Relocated out of state. Subscription cancelled effective Aug 31.",
  },
];

export const MOCK_ADMIN_APPOINTMENTS: AdminAppointment[] = [
  {
    id: "appt_101",
    clientId: "AW-1001",
    clientName: "John Miller",
    clientPhone: "(401) 212-3002",
    clientAddress: "142 Wayland Ave, Providence",
    serviceType: "Safety Oversight",
    date: "2026-09-15",
    timeSlot: "10:00 AM – 12:00 PM",
    status: "scheduled",
    technicianId: "tech_01",
    technicianName: "Marcus Vance",
    bookedBy: "AgeWellRI Admin",
    notes: "Monthly fall prevention and grab-bar integrity check.",
  },
  {
    id: "appt_102",
    clientId: "AW-1002",
    clientName: "Mary Jones",
    clientPhone: "(401) 555-0812",
    clientAddress: "88 Hope Street, Providence",
    serviceType: "Cleaning",
    date: "2026-09-18",
    timeSlot: "11:30 AM – 01:30 PM",
    status: "scheduled",
    technicianId: "tech_02",
    technicianName: "Elena Rostova",
    bookedBy: "Client",
  },
  {
    id: "appt_103",
    clientId: "AW-1004",
    clientName: "Patricia Davis",
    clientPhone: "(401) 555-0911",
    clientAddress: "45 Elmwood Ave, Cranston",
    serviceType: "Safety Oversight",
    date: "2026-09-20",
    timeSlot: "02:00 PM – 04:00 PM",
    status: "scheduled",
    technicianId: "tech_01",
    technicianName: "Marcus Vance",
    bookedBy: "AgeWellRI Admin",
  },
  {
    id: "appt_090",
    clientId: "AW-1001",
    clientName: "John Miller",
    clientPhone: "(401) 212-3002",
    clientAddress: "142 Wayland Ave, Providence",
    serviceType: "Cleaning",
    date: "2026-08-12",
    timeSlot: "10:00 AM – 12:00 PM",
    status: "completed",
    technicianId: "tech_02",
    technicianName: "Elena Rostova",
    bookedBy: "Client",
    reportId: "rep_201",
    reportStatus: "uploaded",
  },
  {
    id: "appt_089",
    clientId: "AW-1002",
    clientName: "Mary Jones",
    clientPhone: "(401) 555-0812",
    clientAddress: "88 Hope Street, Providence",
    serviceType: "Safety Oversight",
    date: "2026-07-28",
    timeSlot: "09:00 AM – 11:00 AM",
    status: "completed",
    technicianId: "tech_01",
    technicianName: "Marcus Vance",
    bookedBy: "AgeWellRI Admin",
    reportId: "rep_202",
    reportStatus: "uploaded",
  },
];

export const MOCK_ADMIN_VISITS: AdminVisit[] = [
  {
    id: "vst_01",
    appointmentId: "appt_101",
    clientId: "AW-1001",
    clientName: "John Miller",
    serviceType: "Safety Oversight",
    date: "2026-09-15",
    technicianName: "Marcus Vance",
    status: "scheduled",
    reportStatus: "pending",
  },
  {
    id: "vst_02",
    appointmentId: "appt_102",
    clientId: "AW-1002",
    clientName: "Mary Jones",
    serviceType: "Cleaning",
    date: "2026-09-18",
    technicianName: "Elena Rostova",
    status: "scheduled",
    reportStatus: "pending",
  },
  {
    id: "vst_03",
    appointmentId: "appt_090",
    clientId: "AW-1001",
    clientName: "John Miller",
    serviceType: "Cleaning",
    date: "2026-08-12",
    technicianName: "Elena Rostova",
    status: "completed",
    reportStatus: "uploaded",
    reportScore: 98,
  },
  {
    id: "vst_04",
    appointmentId: "appt_089",
    clientId: "AW-1002",
    clientName: "Mary Jones",
    serviceType: "Safety Oversight",
    date: "2026-07-28",
    technicianName: "Marcus Vance",
    status: "completed",
    reportStatus: "uploaded",
    reportScore: 92,
  },
];

export const MOCK_ADMIN_REPORTS: AdminReport[] = [
  {
    id: "rep_202",
    clientId: "AW-1001",
    clientName: "John Miller",
    visitId: "vst_04",
    title: "Age Safe® Home Score™ Assessment",
    visitDate: "July 28, 2026",
    score: 92,
    status: "uploaded",
    pdfUrl: "#",
    uploadedAt: "July 29, 2026",
    summary:
      "Overall home environment is safe. Stairwell lighting upgrade recommended.",
  },
  {
    id: "rep_201",
    clientId: "AW-1001",
    clientName: "John Miller",
    visitId: "vst_03",
    title: "Home safety & Cleaning Summary",
    visitDate: "August 12, 2026",
    score: 98,
    status: "uploaded",
    pdfUrl: "#",
    uploadedAt: "August 13, 2026",
    summary: "Completed deep cleaning of main bathroom and kitchen walkways.",
  },
  {
    id: "rep_203",
    clientId: "AW-1002",
    clientName: "Mary Jones",
    visitId: "vst_05",
    title: "Safety Inspection & Grab-Bar Check",
    visitDate: "August 15, 2026",
    status: "pending",
    summary: "Report being drafted by technician Marcus Vance.",
  },
];

export const MOCK_ADMIN_AGREEMENTS: AdminAgreement[] = [
  {
    id: "agr_501",
    clientId: "AW-1001",
    clientName: "John Miller",
    title: "AgeWellRI Member Service Agreement",
    status: "executed",
    signedDate: "August 17, 2026",
    version: "v2.4 - Guardian Plus",
    pdfUrl: "#",
  },
  {
    id: "agr_502",
    clientId: "AW-1003",
    clientName: "Robert Brown",
    title: "AgeWellRI Member Service Agreement",
    status: "pending_signature",
    lastReminderSent: "Aug 16, 2026",
    version: "v2.4 - Guardian Plus",
    pdfUrl: "#",
  },
  {
    id: "agr_503",
    clientId: "AW-1006",
    clientName: "Linda Taylor",
    title: "AgeWellRI Member Service Agreement",
    status: "signed",
    signedDate: "August 15, 2026",
    version: "v2.4 - Guardian Plus",
    pdfUrl: "#",
  },
];

export const MOCK_ADMIN_INVOICES: AdminInvoice[] = [
  {
    id: "inv_301",
    clientId: "AW-1001",
    clientName: "John Miller",
    invoiceNumber: "INV-2026-0601",
    amount: "$495.00",
    planName: "Guardian Plus",
    billingFrequency: "Monthly",
    status: "paid",
    date: "June 1, 2026",
    dueDate: "June 1, 2026",
    paymentMethod: "Visa ending 4242",
  },
  {
    id: "inv_302",
    clientId: "AW-1004",
    clientName: "Patricia Davis",
    invoiceNumber: "INV-2026-0801",
    amount: "$495.00",
    planName: "Guardian Plus",
    billingFrequency: "Monthly",
    status: "failed",
    date: "August 1, 2026",
    dueDate: "August 1, 2026",
    paymentMethod: "Mastercard ending 9110",
  },
  {
    id: "inv_303",
    clientId: "AW-1002",
    clientName: "Mary Jones",
    invoiceNumber: "INV-2026-0601",
    amount: "$295.00",
    planName: "Essential Guard",
    billingFrequency: "Monthly",
    status: "paid",
    date: "June 1, 2026",
    dueDate: "June 1, 2026",
    paymentMethod: "Amex ending 1004",
  },
];

export const MOCK_ADMIN_SUBSCRIPTIONS: AdminSubscription[] = [
  {
    id: "sub_101",
    clientId: "AW-1001",
    clientName: "John Miller",
    planName: "Guardian Plus",
    billingFrequency: "Monthly",
    currentPeriod: "Jun 1, 2026 – Jun 30, 2026",
    renewalDate: "July 1, 2026",
    autoRenew: true,
    paymentMethod: "Visa ending 4242",
    status: "renewing_soon",
    billingStatus: "ready",
    visitSchedulingStatus: "partially_scheduled",
  },
  {
    id: "sub_102",
    clientId: "AW-1004",
    clientName: "Patricia Davis",
    planName: "Guardian Plus",
    billingFrequency: "Monthly",
    currentPeriod: "Jun 1, 2026 – Jun 30, 2026",
    renewalDate: "July 1, 2026",
    autoRenew: true,
    paymentMethod: "Mastercard ending 9110",
    status: "payment_failed",
    billingStatus: "failed",
    visitSchedulingStatus: "not_scheduled",
  },
];

export const MOCK_ADMIN_NOTIFICATIONS: AdminNotification[] = [
  {
    id: "notif_a1",
    title: "New Client Account Created",
    message:
      "Robert Brown (AW-1003) created account. Agreement pending signature.",
    timestamp: "10 mins ago",
    read: false,
    type: "onboarding",
    link: "/admin/clients/AW-1003",
    severity: "info",
  },
  {
    id: "notif_a2",
    title: "Monthly Payment Failed",
    message: "Patricia Davis (AW-1004) payment failed for $495.00.",
    timestamp: "1 hour ago",
    read: false,
    type: "payment",
    link: "/admin/billing",
    severity: "urgent",
  },
  {
    id: "notif_a3",
    title: "Agreement Signed",
    message: "Linda Taylor (AW-1006) signed Member Service Agreement.",
    timestamp: "3 hours ago",
    read: true,
    type: "agreement",
    link: "/admin/agreements",
    severity: "info",
  },
];

export const MOCK_AUDIT_LOGS: AuditActivityLog[] = [
  {
    id: "aud_01",
    clientId: "AW-1001",
    timestamp: "Aug 17, 2026 09:14 AM",
    action: "Agreement Executed",
    performedBy: "System (DocuSign Integration)",
    details: "Member Service Agreement v2.4 executed successfully.",
  },
  {
    id: "aud_02",
    clientId: "AW-1001",
    timestamp: "Aug 17, 2026 10:30 AM",
    action: "Appointment Scheduled",
    performedBy: "Admin (Sarah Jenkins)",
    details: "Scheduled Safety Oversight for Sept 15 with Marcus Vance.",
  },
];
